controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_homepage:
    path: /
    controller: App\Controller\DefaultController::index

handle_call:
    path: /handle-call
    controller: App\Controller\YourController::handleCall